#pragma config(Motor,  port1,           right_motor,   tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           shovel,        tmotorNone, openLoop)
#pragma config(Motor,  port10,          left_motor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int SCALE_FACTOR = 4;

task main()
{
	int r_motor = 0;
	int l_motor = 0;

	for(;;)
	{
		// Normal control joystick
		if(vexRT[Ch1] != 0 || vexRT[Ch2] != 0)
		{
			r_motor = vexRT[Ch1] + vexRT[Ch2];
			l_motor = -vexRT[Ch1] + vexRT[Ch2];

			// Constrain values
			if(r_motor > 127) r_motor = 127;
			if(r_motor < -127) r_motor = -127;
			if(l_motor > 127) l_motor = 127;
			if(l_motor < -127) l_motor = -127;
		}

		// Set motor speed
		motor[right_motor] = r_motor;
		motor[left_motor] = l_motor;

		delay(50);
	}
}
